"""
build_map_data.py

What it does: reads the Society's working spreadsheet and writes hospitals.js,
the small data file the map loads. Only public fields are copied, so internal
notes, survey answers, and conflict-of-interest flags never reach the website.

How to run (from this folder):
    python build_map_data.py /path/to/PFS_hospital_map_data.xlsx

Needs: openpyxl (pip install openpyxl)
"""
import json
import sys
import datetime
from openpyxl import load_workbook

xlsx_path = sys.argv[1] if len(sys.argv) > 1 else "PFS_hospital_map_data.xlsx"
out_path = sys.argv[2] if len(sys.argv) > 2 else "hospitals.js"

# Open the spreadsheet and read the Hospitals tab into a list of dictionaries,
# one per row, keyed by the column headers.
sheet = load_workbook(xlsx_path, data_only=True)["Hospitals"]
headers = [cell.value for cell in sheet[1]]
rows = [dict(zip(headers, [cell.value for cell in row])) for row in sheet.iter_rows(min_row=2)]

def yes(value):
    return str(value).strip().lower() == "yes"

hospitals, skipped = [], []
for r in rows:
    if not r.get("Display_name"):
        continue  # blank line in the sheet
    # Same rule as the Display_status column: hide hospitals that declined to be
    # listed and hospitals with nothing verified yet. Every pin must also have a
    # documented pediatric neurosurgery team (Peds_neurosurgery_service = Yes).
    verified = any(yes(r.get(c)) for c in
                   ["ACPNF_fellowship", "ABPNS_surgeon_on_staff", "COG_member",
                    "iMRI_public_evidence", "Published_CMS_outcomes", "PFS_member_affiliation"])
    declined = str(r.get("Survey_consent_to_publish") or "").strip().lower() == "no"
    has_pin = isinstance(r.get("Latitude"), (int, float)) and isinstance(r.get("Longitude"), (int, float))
    surgical = yes(r.get("Peds_neurosurgery_service"))
    if declined or not verified or not has_pin or not surgical:
        skipped.append(r["Display_name"])
        continue
    last = r.get("Last_verified")
    hospitals.append({
        "id": r["Hospital_ID"],
        "name": r["Display_name"],
        "street": r.get("Street_address") or "",
        "city": r.get("City") or "",
        "state": r.get("State") or "",
        "zip": str(r.get("ZIP") or ""),
        "lat": r["Latitude"],
        "lon": r["Longitude"],
        "acpnf": yes(r.get("ACPNF_fellowship")),
        "abpns": yes(r.get("ABPNS_surgeon_on_staff")),
        "cog": yes(r.get("COG_member")),
        "imri": yes(r.get("iMRI_public_evidence")),
        "published": yes(r.get("Published_CMS_outcomes")),
        "pfsMember": yes(r.get("PFS_member_affiliation")),
        "pfsDisciplines": r.get("PFS_member_disciplines") or "",
        "citation": r.get("Published_citation") or "",
        "citationLink": r.get("Published_link") or "",
        "note": r.get("Public_note") or "",
        "lastVerified": last.strftime("%Y-%m-%d") if hasattr(last, "strftime") else str(last or ""),
    })

stamp = datetime.date.today().isoformat()
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Generated by build_map_data.py on " + stamp + ". Do not edit by hand.\n")
    f.write("window.PFS_DATA_DATE = " + json.dumps(stamp) + ";\n")
    f.write("window.PFS_HOSPITALS = " + json.dumps(hospitals, indent=1, ensure_ascii=False) + ";\n")

print(f"Wrote {len(hospitals)} hospitals to {out_path}")
if skipped:
    print(f"Left off the map ({len(skipped)}): " + "; ".join(skipped))
